development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: development_blog
  pool: 25
  username: root
  password: root
  host: 127.0.0.1
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_blog
  pool: 25
  username: root
  password: root
  host: 127.0.0.1  