development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: development_blog
  pool: 25
  username: root
  password: root
  host: db.local
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_blog
  pool: 25
  username: root
  password: root
  host: db.local  