version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            cd /root/project/blog
            # $(echo docker images)
            docker build -t ruby_app .
            docker run -d --name db -e MYSQL_ROOT_PASSWORD=root mysql:5.5.62
            docker exec -it db sh -c "mysql -uroot -proot -e 'create database test_blog' "
            docker run --name rubybox -it -d --link db:db ruby_app
            docker exec -it rubybox sh -c "bundle install && rake db:migrate RAILS_ENV='test' && rspec  && zip -r own_artifact.zip /usr/src/app/"
            mkdir /root/project/own-artifact && cd /root/project/own-artifact
            docker cp rubybox:/usr/src/app/own_artifact.zip .
            docker login --username=madhantry --password=madhan@docker
            docker tag ruby_app:latest madhantry/mdn-images
            docker push madhantry/mdn-images
      - store_artifacts:
          path: /root/project/own-artifact/own_artifact.zip
          destination: /root/project/own-artifact  
      # - setup_remote_docker:
      #     docker_layer_caching: true
      # - run: docker run -d -p 3000:3000 local:static_rails_app rails s -b 0.0.0.0
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            echo $CIRCLE_BUILD_NUM
            ssh ubuntu@18.209.211.207 BUILD_NO="$CIRCLE_BUILD_NUM" /bin/bash < "/home/circleci/project/blog/scripts/deploy.sh"
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build