version: 2
jobs:
  job1:
    parallelism: 3
    docker:
      - image: ruby:latest
      - image: mysql:5.5.62
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_USER: root  
    steps:
      - checkout
      # - setup_remote_docker:
      #     docker_layer_caching: true
      - run:
          name: job1
          command: |
            echo $CIRCLE_WORKING_DIRECTORY
            cd ~/project/blog
            bundle install --local
            TESTFILES=$(circleci tests glob "~/project/blog/spec/**/*.rb" | circleci tests split)
            bundle exec rspec -- ${TESTFILES}
      # - run:
      #     name: job2
      #     command: |
      #       echo "I m inside the job 2"
      # - run:
      #     name: job3
      #     command: |
      #       echo "I m inside the job 3"                        
  # job2:
  #   docker:
  #     - image: docker
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         docker_layer_caching: true
  #     - run:
  #         name: job2
  #         command: |
  #           echo "I m inside the job 2"   
  # job3:
  #   docker:
  #     - image: docker
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         docker_layer_caching: true
  #     - run:
  #         name: job3
  #         command: |
            # echo "I m inside the job 3"                           
workflows:
  version: 2
  workflow:
    jobs:
      - job1
      # - job2
      # - job3

