version: 2
jobs:
  job1:
    parallelism: 2
    docker:
      - image: ruby:latest
      - image: mysql:5.5.62
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_USER: root  
    steps:
      - checkout
      - run:
          name: Running single job with multiple containers(parallelism example)
          command: |
            echo $CIRCLE_WORKING_DIRECTORY
            mkdir ~/project/blog/test-results
            cd ~/project/blog
            bundle install --local
            bundle exec rake db:create RAILS_ENV=test && bundle exec rake db:migrate RAILS_ENV=test
            TESTFILES=$(circleci tests glob ~/project/blog/spec/models/*.rb | circleci tests split --timings-type=classname)
            echo "SPLITTED TEST FILES LIST FOR THIS CONTAINER "
            echo ${TESTFILES}
            bundle exec rspec -- ${TESTFILES}
      - store_test_results:
          path: ~/project/blog/test-results            
      # - run:
      #     name: job2
      #     command: |
      #       echo "I m inside the job 2"
      # - run:
      #     name: job3
      #     command: |
      #       echo "I m inside the job 3"                        
  # job2:
  #   docker:
  #     - image: docker
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         docker_layer_caching: true
  #     - run:
  #         name: job2
  #         command: |
  #           echo "I m inside the job 2"   
  # job3:
  #   docker:
  #     - image: docker
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         docker_layer_caching: true
  #     - run:
  #         name: job3
  #         command: |
            # echo "I m inside the job 3"                           
workflows:
  version: 2
  workflow:
    jobs:
      - job1
      # - job2
      # - job3

