version: 2
jobs:
  job1:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: job1
          command: |
            echo "I m inside the job 1"
  job2:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: job2
          command: |
            echo "I m inside the job 2"   
  job3:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: job3
          command: |
            echo "I m inside the job 3"                           
# workflows:
#   version: 2
#   workflow:
#     jobs:
#       - security_and_code_quality_check
#       - build:
#           requires:
#             - security_and_code_quality_check
#       - deploy:
#           requires:
#             - build
