version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            cd /root/project/blog
            # $(echo docker images)
            docker build -t madhantry/mdn-images:latest .
            docker login --username=madhantry --password=madhan@docker
            docker tag madhantry/mdn-images madhantry/mdn-images:latest
            docker push madhantry/mdn-images
            exit 0
  deploy:
    docker:
      - image: ruby:2.3-slim
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            sleep 60
            cd /root/project/blog
            bundle install --local 
            ruby scripts/update_ecs_service.rb
            exit 0            
  # deploy:
  #   machine:
  #     enabled: true
  #   steps:
  #     - checkout
  #     - run:
  #         name: Deploy in AWS ECS Fargate
  #         command: |
  #           cd /home/circleci/project/blog/scripts
  #           ruby update_ecs_service.rb
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build

         