version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty 
      - image: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # - run:
      #     command: sudo apt install zip unzip
      - run:
          command: |
            cd /root/project/blog
            sudo docker build -t local:static_rails_app .
            sudo docker run --name rubybox -it -d local:static_rails_app
            sudo docker exec -it rubybox sh -c "bundle install && bundle exec rspec"
            mkdir /root/project/own-artifact && cd /root/project/own-artifact && zip -r own_artifact.zip /root/project/blog
      - store_artifacts:
          path: /root/project/own_artifact.zip
          destination: /root/project/own-artifact  
      # - setup_remote_docker:
      #     docker_layer_caching: true
      # - run: docker run -d -p 3000:3000 local:static_rails_app rails s -b 0.0.0.0

