version: 0.2
env:
  variables:
    unicorn_artifactname: "cync_ror_unicorn"
    cron_artifactname: "cync_ror_cron"
    sidekiq_artifactname: "cync_ror_sidekiq"

phases:
  install:
    commands:
      - echo `pwd`
      - chmod +x blog/scripts/unicorn_artifact.sh blog/scripts/cron_artifact.sh blog/scripts/sidekiq_artifact.sh
  # pre_build:
  #   commands:
  build:
    commands:
      - echo Build started on `date`
      - echo `pwd`
      - timestamp=$(date -u '+%Y-%m-%d_%H-%M-%S_%Z')
      - buildID=$(echo $CODEBUILD_BUILD_ID | awk -F':' '{print $2}')
      - srcVer=$CODEBUILD_SOURCE_VERSION      
      - ./blog/scripts/unicorn_artifact.sh
      - ./blog/scripts/sidekiq_artifact.sh
      - ./blog/scripts/cron_artifact.sh
      - unicorn_artifactname=$(echo $unicorn_artifactname.$buildID.$srcVer.$timestamp)
      - sidekiq_artifactname=$(echo $sidekiq_artifactname.$buildID.$srcVer.$timestamp)
      - cron_artifactname=$(echo $cron_artifactname.$buildID.$srcVer.$timestamp) 
      - tar -zcvf $unicorn_artifactname circleci-poc-unicorn/*
      - tar -zcvf $sidekiq_artifactname circleci-poc-sidekiq/*
      - tar -zcvf $cron_artifactname circleci-poc-cron/*
      - aws s3 cp $unicorn_artifactname s3://multiple-artifacts-test-for-ror/ --sse
      - aws s3 cp $sidekiq_artifactname s3://multiple-artifacts-test-for-ror/ --sse
      - aws s3 cp $cron_artifactname s3://multiple-artifacts-test-for-ror/ --sse
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
      # - circleci-poc-unicorn/
      # - circleci-poc-sidekiq/
      # - circleci-poc-cron/
      # - cync-base/public/version.html
      - $unicorn_artifactname
      - $cron_artifactname
      - $sidekiq_artifactname
      # - ansible_deploy.sh
      # - cleanup_deploy.sh
      # - env.txt
  discard-paths: yes