version: 0.2
env:
  variables:
    unicorn_artifactname: "cync_ror_unicorn"
    cron_artifactname: "cync_ror_cron"
    sidekiq_artifactname: "cync_ror_sidekiq"

phases:
  install:
    commands:
      - echo `pwd`
      - chmod +x blog/scripts/multiple_artifact.sh
  # pre_build:
  #   commands:
  build:
    commands:
      - echo Build started on `date`
      - echo `pwd`
      - chmod +x blog/scripts/multiple_artifact.sh
      - ./blog/scripts/multiple_artifact.sh
      - echo `pwd`
      - echo `ls -la`
      - tar -zcvf $unicorn_artifactname circleci-poc-unicorn/*
      - tar -zcvf $sidekiq_artifactname circleci-poc-sidekiq/*
      - tar -zcvf $cron_artifactname circleci-poc-cron/*
      - echo `ls -la`
      - aws s3 cp $unicorn_artifactname s3://multiple-artifacts-test-ror/ --sse
      - aws s3 cp $sidekiq_artifactname s3://multiple-artifacts-test-ror/ --sse
      - aws s3 cp $cron_artifactname s3://multiple-artifacts-test-ror/ --sse
  post_build:
    commands:
      - echo Build completed on `date`
# artifacts:
#   files:
#       - circleci-poc-unicorn/
#       - circleci-poc-sidekiq/
#       - circleci-poc-cron/
      # - cync-base/public/version.html
      # - appspec.yml
      # - ansible_deploy.sh
      # - cleanup_deploy.sh
      # - env.txt
  # discard-paths: yes